#!/usr/bin/env python3
"""Wrap any command and add clickable OSC 8 jbo:// links to absolute path:line references."""
import fcntl
import os
import pty
import re
import select
import signal
import sys
import termios
import tty

IDE = os.environ.get('JBO_IDE', 'webstorm')

# Only match absolute paths (/mnt/... or /home/...) with a file extension and line number.
# Anchored on / so ANSI sequences (which never start with /) are never matched.
_RE = re.compile(rb'(/[^\x00-\x20\x7f]*\.[a-zA-Z0-9]{1,10}):(\d+)')

def _linkify(m):
    path, line = m.group(1), m.group(2)
    url = b'jbo://open?ide=' + IDE.encode() + b'&file=' + path + b'&line=' + line
    return b'\x1b]8;;' + url + b'\x1b\\' + path + b':' + line + b'\x1b]8;;\x1b\\'

def _sync_winsize(src, dst):
    try:
        fcntl.ioctl(dst, termios.TIOCSWINSZ,
                    fcntl.ioctl(src, termios.TIOCGWINSZ, b'\x00' * 8))
    except OSError:
        pass

def main():
    args = sys.argv[1:]
    if not args:
        sys.exit('Usage: jbo-wrap <command> [args...]')

    pid, master = pty.fork()
    if pid == 0:
        os.execvp(args[0], args)
        sys.exit(1)

    stdout_fd = sys.stdout.fileno()
    stdin_fd  = sys.stdin.fileno()

    _sync_winsize(stdout_fd, master)
    signal.signal(signal.SIGWINCH, lambda *_: _sync_winsize(stdout_fd, master))

    if not os.isatty(stdin_fd):
        sys.exit('jbo-wrap: stdin must be a terminal')
    old_attr = termios.tcgetattr(stdin_fd)
    tty.setraw(stdin_fd)

    try:
        while True:
            try:
                rlist, _, _ = select.select([master, stdin_fd], [], [])
            except (InterruptedError, ValueError):
                break
            if master in rlist:
                try:
                    chunk = os.read(master, 65536)
                except OSError:
                    break
                sys.stdout.buffer.write(_RE.sub(_linkify, chunk))
                sys.stdout.buffer.flush()
            if stdin_fd in rlist:
                try:
                    chunk = os.read(stdin_fd, 1024)
                except OSError:
                    break
                if not chunk:
                    break
                os.write(master, chunk)
    finally:
        termios.tcsetattr(stdin_fd, termios.TCSANOW, old_attr)
        try:
            os.waitpid(pid, 0)
        except ChildProcessError:
            pass

if __name__ == '__main__':
    main()
